# Generated by Django 5.1.6 on 2026-03-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='duration',
            field=models.IntegerField(choices=[(5, '5 sec'), (10, '10 sec'), (60, '1 min'), (600, '10 min'), (3600, '1 hour')]),
        ),
    ]
