# Generated by Django 5.1.6 on 2026-03-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_daily_bonus',
            field=models.DateField(blank=True, null=True),
        ),
    ]
